---
title: "FBI Crime Data Capstone Project Proposal"
author: "Ankita Hanmiah"
date: "November 2, 2018"
output:
  pdf_document: default
  html_document: default
---

### Problem to Solve:
The Federal Bureau of Investigation's Uniform Crime Reporting program contains a plethora of data intended to provide information to law enforcement administration and the public on the prevalence of different crime acts throughout the United States. There are four separate collections of data: national incidents, crimes against law enforcement officials, hate crimes, and general crime. In my project, I'll be focusing on general crime, which includes violent and property crime, with the initiative of answering the following questions: for each of the crimes, which states are they most widespread in? And more specifically within those states, which counties and cities are the crimes most prevalent in? In the highest crime-ridden states, is there a large difference between crime in the big cities and urban areas versus rural towns? Is there a correlation between the rate of poverty and the rate of crime within those states/cities?

### Potential Client and Why This Is Beneficial to Them:
The potential client would be law enforcement and state governments, so that they may be able to more thoroughly understand the most prevailing crime-related, and possibly poverty-related, issues within their jurisdiction. This information could help them build new laws, programs or make reforms that move towards preventing these crimes within their state. 

### Data To Be Used:
The main data I will be using for this project will be the 2017 FBI UCR Crime in the United States data tables provided on the FBI's website. I will also be pulling poverty data from the United States Census Bureau.

### Outline of Approach:
*Pull only the data from 2017 (as 2016 data is also included in the tables) and arrange the fifty states alphabetically with the number totals for each of the crimes

*Gather the number of offenses and the rate into two new columns, "Offenses" and "Rate"

*Arrange the poverty data by states alphabetically and append the number and percent of people in poverty to the crime data

*Plot crime versus poverty to see if there is a correlation

*Pull data for the states with the highest crime rates and look at specific counties, appending the county poverty data from the US Census, and comparing the metropolitan areas to the nonmetropolitan

### Deliverables:
The deliverables would be the tables, code, and plots used to accomplish what has been set out in this proposal, along with a write-up defining the usefulness of the data and project for the client.

